<?php

/**
 * PluginSchedule
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    opCalendarPlugin
 * @subpackage model
 * @author     Shinichi Urabe <urabe@tejimaya.com>
 */
abstract class PluginSchedule extends BaseSchedule
{
  public function isShowable($memberId)
  {
    return $this->isEditable($memberId) || $this->isScheduleMember($memberId);
  }

  public function isScheduleMember($memberId)
  {
    $scheduleMemberIds = Doctrine::getTable('ScheduleMember')->getMemberIdsBySchedule($this);
    foreach ($scheduleMemberIds as $scheduleMemberId)
    {
      if ($scheduleMemberId === $memberId)
      {
        return true;
      }
    }

    return false;
  }

  public function isEditable($memberId)
  {
    return $this->getMemberId() === $memberId;
  }
}
