<?php

/**
 * PluginScheduleGroupMemberTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginScheduleGroupMemberTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginScheduleGroupMemberTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginScheduleGroupMember');
    }
}