<?php

/**
 * PluginSchedule
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class PluginSchedule extends BaseSchedule
{
  public function isEditable($memberId)
  {
    return $this->getMemberId() === $memberId;
  }
}
