<?php

/**
 * PluginScheduleMember
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    opCalendarPlugin
 * @subpackage model
 * @author     Shinichi Urabe <urabe@tejimaya.com>
 */
abstract class PluginScheduleMember extends BaseScheduleMember
{

}
