<?php

/**
 * PluginScheduleResourceLockTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginScheduleResourceLockTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginScheduleResourceLockTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginScheduleResourceLock');
    }
}