<?php

/**
 * PluginScheduleResource
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    OpenPNE
 * @subpackage opCalendarPlugin
 * @author     Shinichi Urabe <urabe@tejimaya.com>
 */
abstract class PluginScheduleResource extends BaseScheduleResource
{
  public function preSave($event)
  {
    if ($this->isNew())
    {
      $sfUser = sfContext::getInstance()->getUser();
      if ('pc_backend' == sfConfig::get('sf_app') && $backend_id = $sfUser->getId())
      {
        $this->setAdminUserId($backend_id);
      }
      elseif ($frontend_id = $sfUser->getMemberId())
      {
        $this->setMemberId($frontend_id);
      }
    }
  }
}
