<?php

/**
 * PluginScheduleResourceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginScheduleResourceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginScheduleResourceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginScheduleResource');
    }
}