general:
  calendar_show_flag:
    Name:       "calendar_show_flag"
    Caption:    "Calendar Show Flag"
    FormType:   "radio"
    ValueType:  "string"
    IsUnique:   false
    IsRequired: true
    Default:    "none"
    Choices:
      all:                      "All %community% Member's opened Schedule and %community% Event"
      only_member_schedule:     "Only Member's opend Schedule"
      only_community_event:     "Only %community% Event"
      none:                     "Invalidate a calendar"
