holiday:
  url: /holiday
  param: { module: holiday, action: list }

holiday_create:
  url: /holiday/create
  class: sfRequestRoute
  param: { module: holiday, action: create }
  requirements:
    sf_method: [post]

holiday_update:
  url: /holiday/update/:id
  class: sfDoctrineRoute
  options: { model: Holiday, type: object }
  param: { module: holiday, action: update }
  requirements:
    id: \d+
    sf_method: [put]

holiday_delete:
  url: /holiday/delete/:id
  class: sfDoctrineRoute
  options: { model: Holiday, type: object }
  param: { module: holiday, action: delete }
  requirements:
    id: \d+
    sf_method: [post]

holiday_nodefaults:
  url: /holiday/*
  param: { module: default, action: error }

opCalendarPlugin:
  url: /opCalendarPlugin
  param: { module: opCalendarPlugin, action: index }

opCalendarPlugin_resource_create:
  url: /opCalendarPlugin/resourceCreate
  class: sfRequestRoute
  param: { module: opCalendarPlugin, action: resourceCreate }
  requirements:
    sf_method: [post]

opCalendarPlugin_resource_update:
  url: /opCalendarPlugin/resourceUpdate/:id
  class: sfDoctrineRoute
  options: { model: ScheduleResource, type: object }
  param: { module: opCalendarPlugin, action: resourceUpdate }
  requirements:
    id: \d+
    sf_method: [put]

opCalendarPlugin_resource_delete_confirm:
  url: /opCalendarPlugin/resourceDeleteConfirm/:id
  class: sfDoctrineRoute
  options: { model: ScheduleResource, type: object }
  param: { module: opCalendarPlugin, action: resourceDeleteConfirm }
  requirements:
    id: \d+

opCalendarPlugin_resource_delete:
  url: /opCalendarPlugin/resourceDelete/:id
  class: sfDoctrineRoute
  options: { model: ScheduleResource, type: object }
  param: { module: opCalendarPlugin, action: resourceDelete }
  requirements:
    id: \d+
    sf_method: [delete]

opCalendarPlugin_resource_type_create:
  url: /opCalendarPlugin/resourceTypeCreate
  class: sfRequestRoute
  param: { module: opCalendarPlugin, action: resourceTypeCreate }
  requirements:
    sf_method: [post]

opCalendarPlugin_resource_type_update:
  url: /opCalendarPlugin/resourceTypeUpdate/:id
  class: sfDoctrineRoute
  options: { model: ResourceType, type: object }
  param: { module: opCalendarPlugin, action: resourceTypeUpdate }
  requirements:
    id: \d+
    sf_method: [put]

opCalendarPlugin_resource_type_delete_confirm:
  url: /opCalendarPlugin/resourceTypeDeleteConfirm/:id
  class: sfDoctrineRoute
  options: { model: ResourceType, type: object }
  param: { module: opCalendarPlugin, action: resourceTypeDeleteConfirm }
  requirements:
    id: \d+

opCalendarPlugin_resource_type_delete:
  url: /opCalendarPlugin/resourceTypeDelete/:id
  class: sfDoctrineRoute
  options: { model: ResourceType, type: object }
  param: { module: opCalendarPlugin, action: resourceTypeDelete }
  requirements:
    id: \d+
    sf_method: [delete]

opCalendarPlugin_google_data_api_update:
  url: /opCalendarPlugin/googleDataAPIUpdate
  class: sfRequestRoute
  param: { module: opCalendarPlugin, action: googleDataAPIUpdate }
  requirements:
    sf_method: [post]

opCalendarPlugin_nodefaults:
  url: /opCalendarPlugin/*
  param: { module: default, action: error }
